project:
  type: book
  output-dir: _book

book:
  title: "A Visual Refresher on AWS Cloud Fundamentals"
  author: "Senthil Kumar"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-security.qmd
    - 03-compute.qmd
    - 04-networking.qmd
    - 05-storage.qmd
    - 06-databases.qmd
    - 07-monitoring.qmd
    - 08-optimization.qmd
    - 09-references-disclosure.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    includes:
      in_header: _includes/navbar-right.html
    navbar:
      right:
        - text: "Blog"
          href: "https://senthilkumarm1901.github.io/learn_by_blogging/blog.html"
          target: _self
        - text: "LinkedIn"
          href: "https://www.linkedin.com/"
          target: _blank
        - text: "Medium"
          href: "https://medium.com/"
          target: _blank