project:
  type: book
  output-dir: _book

book:
  title: "AWS Technical Essentials"
  author: "Senthil Kumar"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-security.qmd
    - 03-compute.qmd
    - 04-networking.qmd
    - 05-storage.qmd
    - 06-databases.qmd
    - 07-monitoring.qmd
    - 08-optimization.qmd
    - 09-references-disclosure.qmd

format:
  html:
    theme: cosmo